name: TypeScript SDK Tests

on:
  push:
    branches:
      - main
    paths:
      - 'packages/sdk-ts/**'
  pull_request:
    branches:
      - main
    paths:
      - 'packages/sdk-ts/**'

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install Dependencies
        working-directory: packages/sdk-ts
        run: bun install

      - name: Run Tests
        working-directory: packages/sdk-ts
        run: bun run test